version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      jdbc_url: "jdbc:mysql://database/bookstore?createDatabaseIfNotExist=true&amp;amp;useUnicode=true&amp;amp;characterEncoding=utf-8&amp;amp;autoReconnect=true"
      jdbc_username: root
      jdbc_password: toor
    container_name: webapp
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    container_name: database